### ISSUE TITLE
JSON result should structure the predicted class label

### ISSUE THREAD

**Issue by hlapp** [Imageomics/pybioclip#1]
For JSON output what I had in mind was passing through the structured information in the predicted label to the extent that we have it and can easily match it from the cached `txt_emb_species.json` file. Something like this:
```json
[
  { "classification": { 
      "kingdom": "Animalia", 
      "phylum": "Chordata",
      "class": "Mammalia",
      "order": "Carnivora",
      "family": "Ursidae",
      "genus": "Ursus",
      "species_epithet": "arctos",
      "species": "Ursus arctos",
      "common_name": "Kodiak bear"
    },
   "score": 0.82264
  },
...
]
```
In the same manner, can we allow the predicted classification to be returned in structured format (a dict corresponding to the above, for example).

The motivation is that right now by passing it back as the concatenated string we're in essence asking the user to parse it themselves (because a user would very often not want to output the complete unstructured string), whereas it seems that we can do that more easily than they can because we have the `txt_emb_species.json` in our hands.

Alternatively, we could instead also expose a lookup function that takes a concatenated class label string as input and using the `txt_emb_species.json` cache returns a dict following the above.

**Comment by johnbradley** [comment]
I really like this. This idea also be nice for the table/csv outputs. The name strung together is rather hard to look at.
