### ISSUE TITLE
Convert Image to RGB

### ISSUE THREAD

**Issue by yanis-falaki** [Imageomics/pybioclip#12]
I encountered errors when using PNG images, and discovered that it's because it's read as RGBA instead of RGB, and so it messes with the preprocess_img transforms (line 121).
This is fixed by forcing the image to RGB on line 182 and 290, so that goes from
`img = PIL.Image.open(image_path)`
to
`img = PIL.Image.open(image_path).convert("RGB")`

This is the error:
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

**Comment by johnbradley** [comment]
Thanks @yanis-falaki. I created PR #13 with your fix and added you as a co-author on the commit.
