### ISSUE TITLE
Allow providing custom bins for summing scores

### ISSUE THREAD

**Issue by hlapp** [Imageomics/pybioclip#29]
The `--rank` option allows summing scores over a particular rank. In essence, the taxonomic groups at that rank serve as bins for scores, and scores are then summed over all predictions that fall into the bin.

It would be useful to allow providing custom 'bins' for this purpose, especially when supplying a custom list of classes between which to predict, which cannot be used in conjunction with `--rank` (because we can't really know how to bin by a given rank). 

One way to provide a custom binning when using custom classes would be a simple mapping file (custom class to custom bin).

**Comment by johnbradley** [comment]
Ideas: First column is what the user wants to bin. Second column is the name of the bin for that item.
```
Species,bin
Orthomiella rantaizana,bin1
Orthomiella sinensis,bin2
```

```
Genus,binName
```

**Comment by johnbradley** [comment]
NOTE: --binfile would supply the classes. This would be instead of the --cls argument.
