### ISSUE TITLE
Load model checkpoint with `weights_only=True`

### ISSUE THREAD

**Issue by hlapp** [Imageomics/pybioclip#32]
On recent versions of PyTorch the following warning is issued:
```
FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=map_location)
```
Do we _need_ anything else than the weights? I.e., should we be able to set `weights_only=True` or are we currently relying on the default value of `False`?

**Comment by hlapp** [comment]
Turns out this warning is coming from a call from within the `open_clip` library, and it's the invocation within that library that would need to be updated. The only option we have here is to suppress this warning, possibly like so:
```python
import warnings

# Suppress only FutureWarning messages
warnings.simplefilter(action='ignore', category=FutureWarning)

# Code that may produce FutureWarnings
# ...
# ...
# Re-enable all warnings
warnings.resetwarnings()
```

@johnbradley thoughts on whether this is worth doing?

**Comment by johnbradley** [comment]
> thoughts on whether this is worth doing?

@hlapp I would rather leave the warning in and upgrade open_clip when this is resolved there. I'm wondering if there is an issue for this in open_clip.

**Comment by hlapp** [comment]
I can't find it as an issue there.

**Comment by johnbradley** [comment]
I created issue https://github.com/mlfoundations/open_clip/issues/928.

**Comment by johnbradley** [comment]
[Pytorch docs about security](https://github.com/pytorch/pytorch/blob/main/SECURITY.md#using-pytorch-securely). 
> Loading un-trusted checkpoint with weights_only=False MUST never be done.


The model files (open_clip_pytorch_model.bin or *.pt) are pickled python code. Right now, by default, you are running whatever code is in the model file and not just reading model weights. The docs say that [safetensors](https://huggingface.co/docs/safetensors/en/index) provides the safest option, but results in more restrictions.

**Comment by johnbradley** [comment]
You can supress the `weights_only` flag via the [pytorch TORCH_FORCE_WEIGHTS_ONLY_LOAD environment variable](https://pytorch.org/docs/stable/miscellaneous_environment_variables.html):
```
export TORCH_FORCE_WEIGHTS_ONLY_LOAD=true
bioclip predict ...
```
In brief testing everything seems to work fine.

**Comment by hlapp** [comment]
So maybe we can just set that through `os.environ` if it's not set already (so that people could override it in case some models actually need it to be false)?
