### ISSUE TITLE
Add citation recommendations that include citing the BioCLIP paper

### ISSUE THREAD

**Issue by hlapp** [Imageomics/pybioclip#4]
Also, we'll want a _Citation_ section in the README (such as at the end) that asks that users not only cite this code but also the BioCLIP paper, I think. But I can make that a separate follow-up issue.

_Originally posted by @hlapp in https://github.com/Imageomics/pybioclip/pull/3#pullrequestreview-1969536022_

**Comment by johnbradley** [comment]
My understanding this requires 3 changes:
- Archive the repo in Zenodo to create a DOI
- Create a CITATION.cff file using the DOI
- Update readme with the citation details

In hindsight it would have been better to setup Zenodo before creating our first release.

I went into Zenodo and did not see this repo or any Imageomics repos under the list I can add.
Perhaps only Imageomics owners can setup the repo within Zenodo.
@thompsonmj Can you see this repo [within Zenodo](https://zenodo.org/account/settings/github/)?

**Comment by egrace479** [comment]
> My understanding this requires 3 changes:
> 
> * Archive the repo in Zenodo to create a DOI
> * Create a CITATION.cff file using the DOI
> * Update readme with the citation details
> 
> In hindsight it would have been better to setup Zenodo before creating our first release.
> 
> I went into Zenodo and did not see this repo or any Imageomics repos under the list I can add. Perhaps only Imageomics owners can setup the repo within Zenodo. @thompsonmj Can you setup this repo [within Zenodo](https://zenodo.org/account/settings/github/)?

I can turn it on. Based on my experience with archiving Andromeda on Zenodo, we should just set it up with the release and ask them to import the earlier versions after the record is created.

**Comment by johnbradley** [comment]
Fixed by #25
