### ISSUE TITLE
Expose a ability to obtain image embeddings

### ISSUE THREAD

**Issue by hlapp** [Imageomics/pybioclip#6]
The embedding for an image ("image features") is already being calculated, just not available through the API. However, there may well be use cases needing it, such as semantic clustering, vector similarity-driven search etc.

On the command line this could like the following:
```sh
bioclip embed Ursus-arctos.jpeg
```

I suppose in principle one could make the same argument for obtaining text embeddings from the model.

**Comment by johnbradley** [comment]
How should we save the embeddings? It looks like the image embedding is an array of 512 numbers.
The tree of life classification code uses text embeddings that are stored in a npy file [txt_emb_species.npy](https://huggingface.co/spaces/imageomics/bioclip-demo/blob/main/txt_emb_species.npy).

**Comment by johnbradley** [comment]
@hlapp How would you like the JSON to be structured?
Like this?
```
{
   "Ursus-arctos.jpeg": [-2.3634e-01, -2.8467e-01, -4.3945e-01,  5.2463e-01,  2.2815e-01,
         -3.7336e-02,  1.3933e-01,  5.4304e-03,  8.9809e-01,  8.8136e-01,
          3.5307e-01, -5.0572e-01, -1.6550e-02,  1.6668e-01, -3.9064e-02,
          4.1843e-03, -4.4934e-01, -3.1160e-02, -4.6801e-01,  6.1199e-01,
          9.8816e-01,  9.8966e-01,  5.2472e-01, -6.4909e-01,  2.4330e-01,...]
}
```

**Comment by hlapp** [comment]
Yes, that's more or less what I had in mind. I think we'd want to include some kind of reference to the model that was used. At a minimum this would presumably be the URL used for downloading the model in the first place. In addition or alternatively, perhaps name and version or a HF identifier, though if there's a HF repository URL, the rest is presumably implied.
